env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  indent: [error, 4],
  no-plusplus: off,
  linebreak-style: off,
  max-classes-per-file: off,
  no-unused-vars: [error, { argsIgnorePattern: "^_" }],
  class-methods-use-this: [error, { exceptMethods: ["update", "drawOn"] }],
  max-len: [error, 100]
}
